on:
  push:
    tags:
      - 'v*.*.*'

# permissions:
#   contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore OverlayApp.csproj

      - name: Build and publish
        run: dotnet publish OverlayApp.csproj -c Release -r win-x64 --self-contained true -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OverlayApp
          path: publish


  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: OverlayApp
          path: publish

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: publish/OverlayApp.exe
