name: Build and Release .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Specify your .NET version

      - name: Restore dependencies
        run: dotnet restore .\OverlayApp.csproj

      - name: Build and publish
        run: dotnet publish .\OverlayApp.csproj -c Release -r win-x64 --self-contained true -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OverlayApp
          path: ./publish

  release:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: OverlayApp

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./OverlayApp.exe